FROM node:18.15.0-alpine3.17

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install

ADD .eslintrc.json .prettierrc.json index.ts nodemon.json tsconfig.json ./

CMD ["npm", "run", "dev"]
