FROM node:18.15.0-alpine3.17

RUN apk --no-cache add python3 make g++

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install

ADD .env .eslintrc.json .prettierignore .prettierrc.json index.ts tsconfig.json ./

CMD ["npm", "run", "dev"]
